SELECT TRANS_LIQUIDITY_TRACKER.BASE_DATE,
BOND_SPECS.BOND_NAME AS STOCK_NAME, BOND_SPECS.BOND_CODE AS STOCK_CODE, 
CORPORATIONS.CORPORATION_NAME AS ISSUER_NAME,BOND_FACILITIES.FACILITY_NAME AS FACILITY_NAME, 
BOND_OUTSTANDING_AMTS.OUTSTANDING_AMOUNT AS OUTSTANDING_AMOUNT,
TRANS_LIQUIDITY_TRACKER.LIQ_TRADE_RECENCY AS TRADE_RECENCY, TRANS_LIQUIDITY_TRACKER.LIQ_TRADE_FREQ AS TRADE_FREQUENCY, 
TRANS_LIQUIDITY_TRACKER.LIQ_TURNOVER AS TRADE_TURNOVER, TRANS_LIQUIDITY_TRACKER.COMP_LIQ_SCORE AS COMPOSITE_LIQUIDITY_SCORE
FROM BOND_OUTSTANDING_AMTS
INNER JOIN BOND_SPECS ON BOND_OUTSTANDING_AMTS.PROD_CODE = BOND_SPECS.PROD_CODE
INNER JOIN CORPORATIONS ON CORPORATIONS.CORPORATION_CODE = BOND_SPECS.ISSUER_CODE
INNER JOIN BOND_FACILITIES ON BOND_FACILITIES.FACILITY_CODE = BOND_SPECS.FACILITY_CODE
INNER JOIN TRANS_LIQUIDITY_TRACKER ON TRANS_LIQUIDITY_TRACKER.PROD_CODE = BOND_SPECS.PROD_CODE
WHERE TRANS_LIQUIDITY_TRACKER.BASE_DATE >= DATE '2022-04-28'
AND TRANS_LIQUIDITY_TRACKER.BASE_DATE <= DATE '2023-04-28'
AND BOND_SPECS.BOND_CODE IN ('VN130038', 'PK170007', 'PZ190011', 'VG190116', 'VI180294', 'VN130039', 'VZ140131', 'VT220030' , 'VH220026', 'VZ200021')
ORDER BY TRANS_LIQUIDITY_TRACKER.BASE_DATE DESC;