SELECT MIR_CONSTITUENTS_BOND.BASE_DATE,
BOND_RATINGS2.PROD_CODE,
BOND_SPECS.BOND_CODE,
BOND_RATINGS2.RATING_AGENCY_CODE AS RATING_AGENCY,
MIR_CONSTITUENTS_BOND.MIR_CLASS_NODE AS BIR,
RATING_CODES.RATING_CODE_NAME AS RATING, MIR_CONSTITUENTS_BOND.MIR_NOTCH_VARIANCE AS NOTCH_VARIANCE
FROM BOND_RATINGS2
INNER JOIN MIR_CONSTITUENTS_BOND ON MIR_CONSTITUENTS_BOND.PROD_CODE = BOND_RATINGS2.PROD_CODE
INNER JOIN RATING_CODES ON RATING_CODES.RATING_CODE = BOND_RATINGS2.RATING_CODE
INNER JOIN BOND_SPECS ON BOND_SPECS.PROD_CODE = MIR_CONSTITUENTS_BOND.PROD_CODE
WHERE MIR_CONSTITUENTS_BOND.BASE_DATE >= DATE '2022-04-28' 
AND MIR_CONSTITUENTS_BOND.BASE_DATE <= DATE '2023-04-28'
AND BOND_SPECS.BOND_CODE IN ('VN130038', 'PK170007', 'PZ190011', 'VG190116', 'VI180294', 'VN130039', 'VZ140131', 'VT220030' , 'VH220026', 'VZ200021')
ORDER BY MIR_CONSTITUENTS_BOND.BASE_DATE DESC;