SELECT *
FROM (
    -- First statement
    SELECT DISTINCT TRANS_LIQUIDITY_TRACKER.BASE_DATE,
        BOND_SPECS.BOND_NAME, BOND_SPECS.BOND_CODE, 
        CORPORATIONS.CORPORATION_NAME AS ISSUER_NAME, BOND_FACILITIES.FACILITY_NAME AS FACILITY_NAME, 
        BOND_OUTSTANDING_AMTS.OUTSTANDING_AMOUNT AS OUTSTANDING_AMOUNT,
        TRANS_LIQUIDITY_TRACKER.LIQ_TRADE_RECENCY AS TRADE_RECENCY, TRANS_LIQUIDITY_TRACKER.LIQ_TRADE_FREQ AS TRADE_FREQUENCY, 
        TRANS_LIQUIDITY_TRACKER.LIQ_TURNOVER AS TRADE_TURNOVER, TRANS_LIQUIDITY_TRACKER.COMP_LIQ_SCORE AS COMPOSITE_LIQUIDITY_SCORE
    FROM BOND_OUTSTANDING_AMTS
    INNER JOIN BOND_SPECS ON BOND_OUTSTANDING_AMTS.PROD_CODE = BOND_SPECS.PROD_CODE
    INNER JOIN CORPORATIONS ON CORPORATIONS.CORPORATION_CODE = BOND_SPECS.ISSUER_CODE
    INNER JOIN BOND_FACILITIES ON BOND_FACILITIES.FACILITY_CODE = BOND_SPECS.FACILITY_CODE
    INNER JOIN TRANS_LIQUIDITY_TRACKER ON TRANS_LIQUIDITY_TRACKER.PROD_CODE = BOND_SPECS.PROD_CODE
    WHERE TRANS_LIQUIDITY_TRACKER.BASE_DATE >= DATE '2022-04-28'
        AND TRANS_LIQUIDITY_TRACKER.BASE_DATE <= DATE '2023-04-28'
        AND TRANS_LIQUIDITY_TRACKER.LOOKBACK_MONTH = '1M'
        AND NOT CORPORATIONS.CORPORATION_NAME = 'Government of Malaysia'
)statement1
INNER JOIN (
    -- Second statement
    SELECT DISTINCT MIR_CONSTITUENTS_BOND.BASE_DATE,
        BOND_RATINGS2.PROD_CODE,
        BOND_SPECS.BOND_CODE,
        MIR_CONSTITUENTS_BOND.MIR_NOTCH_VARIANCE AS NOTCH_VARIANCE
    FROM BOND_RATINGS2
    INNER JOIN MIR_CONSTITUENTS_BOND ON MIR_CONSTITUENTS_BOND.PROD_CODE = BOND_RATINGS2.PROD_CODE
    INNER JOIN RATING_CODES ON RATING_CODES.RATING_CODE = BOND_RATINGS2.RATING_CODE
    INNER JOIN BOND_SPECS ON BOND_SPECS.PROD_CODE = MIR_CONSTITUENTS_BOND.PROD_CODE
    WHERE MIR_CONSTITUENTS_BOND.BASE_DATE >= DATE '2022-04-28' 
        AND MIR_CONSTITUENTS_BOND.BASE_DATE <= DATE '2023-04-28'
)statement2
ON statement1.BOND_CODE = statement2.BOND_CODE AND statement1.BASE_DATE = statement2.BASE_DATE
ORDER BY statement1.BASE_DATE DESC;
